/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const PrizesLazyImport = createFileRoute('/prizes')()
const DrawLazyImport = createFileRoute('/draw')()

// Create/Update Routes

const PrizesLazyRoute = PrizesLazyImport.update({
  id: '/prizes',
  path: '/prizes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/prizes.lazy').then((d) => d.Route))

const DrawLazyRoute = DrawLazyImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/draw.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawLazyImport
      parentRoute: typeof rootRoute
    }
    '/prizes': {
      id: '/prizes'
      path: '/prizes'
      fullPath: '/prizes'
      preLoaderRoute: typeof PrizesLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draw': typeof DrawLazyRoute
  '/prizes': typeof PrizesLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draw': typeof DrawLazyRoute
  '/prizes': typeof PrizesLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/draw': typeof DrawLazyRoute
  '/prizes': typeof PrizesLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/draw' | '/prizes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/draw' | '/prizes'
  id: '__root__' | '/' | '/draw' | '/prizes'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawLazyRoute: typeof DrawLazyRoute
  PrizesLazyRoute: typeof PrizesLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawLazyRoute: DrawLazyRoute,
  PrizesLazyRoute: PrizesLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/draw",
        "/prizes"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/draw": {
      "filePath": "draw.lazy.tsx"
    },
    "/prizes": {
      "filePath": "prizes.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
